name: maplibre_gl_web
description: Web platform implementation of maplibre_gl
version: 0.10.0
homepage: https://github.com/m0nac0/flutter-maplibre-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/m0nac0/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
  mapbox_gl_dart: ^0.1.5
  image: ^2.1.12

dependency_overrides:
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <2.12.0"
  flutter: ">=1.12.13+hotfix.4"
